//falar qual é o formato dos dados para o json
//arquivo routes.http

POST http://localhost:3333/videos
Content-Type: application/json

{
    "title":"video 5",
    "description": "esse é o quinto video",
    "duration": 170

}

###

GET http://localhost:3333/videos

###


PUT http://localhost:3333/videos/dbc7cce6-1c75-4b26-b127-9f2b8532821b
Content-Type: application/json

{
    "title": "video 5",
    "description": "esse é o quinto video",
    "duration": 170
}

###

DELETE http://localhost:3333/videos/dbc7cce6-1c75-4b26-b127-9f2b8532821b